# Production environment overrides
image:
  repository: namvu24/babymilk
  tag: "stable"
  pullPolicy: IfNotPresent

replicaCount: 2

ingress:
  enabled: true
  className: ""
  host: ""

nginx:
  enabled: true

postgresql:
  enabled: true
  auth:
    username: babymilk
    database: babymilk
  persistence:
    size: 5Gi
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 512Mi

secrets:
  db:
    create: false
    name: babymilk-db
    key: DATABASE_URL
  postgresql:
    create: false
    name: babymilk-postgresql
    userKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD
    databaseKey: POSTGRES_DB
