# k3d local development overrides

image:
  repository: namvu24/babymilk
  tag: main-c6c5128
  pullPolicy: Always

ingress:
  enabled: true
  className: traefik
  host: ""

nginx:
  enabled: true
  cacheControl:
    html: "no-cache, no-store, must-revalidate"
    static: "public, max-age=60"

postgresql:
  enabled: true
