{{- if .Values.secrets.db.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "babymilk.dbSecretName" . }}
  labels:
    {{- include "babymilk.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "babymilk.databaseURL" . | quote }}
{{- end }}

{{- if .Values.secrets.gemini.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "babymilk.geminiSecretName" . }}
  labels:
    {{- include "babymilk.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.gemini.key }}: {{ .Values.secrets.gemini.value | quote }}
{{- end }}
