apiVersion: v1
kind: Secret
metadata:
  name: {{ include "milkapp.fullname" . }}-db
  labels:
    {{- include "milkapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "milkapp.databaseURL" . | quote }}
