apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: babymilk-postgresql
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: babymilk-vault
  target:
    name: babymilk-postgresql
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        POSTGRES_USER: babymilk
        POSTGRES_PASSWORD: "{{ .dbpassword }}"
        POSTGRES_DB: babymilk
  data:
    - secretKey: dbpassword
      remoteRef:
        key: babymilk/postgresql
        property: dbpassword
