apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: babymilk-db
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: babymilk-vault
  target:
    name: babymilk-db
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DATABASE_URL: postgres://babymilk:{{ .dbpassword }}@babymilk-postgresql:5432/babymilk?sslmode=disable
  data:
    - secretKey: dbpassword
      remoteRef:
        key: babymilk/postgresql
        property: dbpassword
