apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: babymilk-gemini
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: babymilk-vault
  target:
    name: babymilk-gemini
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        GEMINI_API_KEY: "{{ .apikey }}"
  data:
    - secretKey: apikey
      remoteRef:
        key: babymilk/gemini
        property: apikey
