apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: milkapp-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/namvu24/milkapp-deploy.git
    targetRevision: main
    path: charts/milkapp
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: milkapp-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
