{{- if and .Values.postgresql.enabled .Values.secrets.postgresql.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "babymilk.postgresqlSecretName" . }}
  labels:
    {{- include "babymilk.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
{{- end }}
